added manual species sync and auto sync after 90 days
Plant-for-the-Planet-org/treemapper pull request #416
Opened 2021-07-13 12:15 UTC by ankitecd

Changes in this pull request:
-  Fixed crash when user is not logged in and goes to TreeInventory
- Added button in ManageSpecies which allow user to manual do scientific species sync
- Added auto scientific species sync after 90 days

@norbertschuler this can go with new release. A crash is also fixed in the same

2021-07-14 09:42 UTC, norbertschuler commented
> * Added auto scientific species sync after 90 days

I tried to test this by modifying the time before an update is triggered, but I cannot see when https://github.com/Plant-for-the-Planet-org/treemapper/blob/569e524d044e032dabc6164d995b4f3fa40233b9/app/components/InitialLoading/index.js#L80 is called if the species list is already downloaded once.

2021-07-14 09:58 UTC, norbertschuler commented
Merged develop to avoid double testing.

2021-07-14 10:18 UTC, ankitecd commented
> Not sure if the code above this line needs to be adapted too at
> 
> https://github.com/Plant-for-the-Planet-org/treemapper/blob/569e524d044e032dabc6164d995b4f3fa40233b9/app/components/InitialLoading/index.js#L61-L68

Yes it should. Will make the change

2021-07-22 09:55 UTC, norbertschuler requested changes

2021-07-22 09:55 UTC, norbertschuler commented on app/utils/ScientificSpecies/shouldUpdateSpeciesSync.ts
> +    differenceNoOfDays = differenceNoOfDays * (1000 * 60 * 60 * 24);
This should be rather `differenceNoOfDays / (1000 * 60 * 60 * 24); ` as otherwise the sync would be done every day!

2021-07-22 09:59 UTC, norbertschuler commented on app/utils/ScientificSpecies/shouldUpdateSpeciesSync.ts
> +    differenceNoOfDays = differenceNoOfDays * (1000 * 60 * 60 * 24);
Fixed it. @ankitecd please check.

2021-07-22 10:04 UTC, norbertschuler approved these changes
Works for me now.

2021-07-22 13:10 UTC, tejassonar approved these changes

2021-07-22 13:10 UTC, merged