added project site navigation for ROs
Plant-for-the-Planet-org/treemapper pull request #526
Opened 2021-11-24 09:43 UTC by ankitecd

2021-12-01 11:55 UTC, norbertschuler commented on app/components/MainScreen/ProjectAndSiteSelector.tsx
> +      setSiteBounds([]);
Got a crash here:
![Simulator Screen Shot - iPhone 13 - 2021-12-01 at 12 54 17](https://user-images.githubusercontent.com/1532418/144230168-d0eb0257-aa5c-47e6-a530-1d1edc6a210f.png)

2021-12-01 12:00 UTC, norbertschuler commented on app/components/MainScreen/ProjectAndSiteSelector.tsx
> +      setSiteCenterCoordinate(turfCenter(JSON.parse(project.geometry)).geometry.coordinates);
The code also crash here with a JSON.parse error as project.geometry was undefined.

2021-12-01 12:04 UTC, norbertschuler requested changes
Starting the app with existing data before, produces the above errors. If you start with a clean app, the native part of MapBox code crashes with:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'A multipoint must have at least one vertex.'
abort() called
```

2021-12-03 12:27 UTC, ankitecd commented
@norbertschuler I tested it on iOS and Android, it's working for me. Can you check again and let me know if it's working for you?

2021-12-17 15:48 UTC, norbertschuler commented
- [ ] The box showing "pending uploads" is not rendered very nice any more:

![Simulator Screen Shot - iPhone 13 - 2021-12-17 at 16 47 31](https://user-images.githubusercontent.com/1532418/146571026-d3f17f47-79b2-466c-8948-6b46577a07ff.png)

2021-12-17 15:57 UTC, norbertschuler approved these changes
PR works for me. Now if you have chosen a project on the map, you just wonder why the chosen project is not automatically used for new registrations. That would be a future enhancement maybe? But as the chosen project also is not made persistent anyway (you always get set back to your first project after killing the app), it does not have priority for me.

2021-12-20 10:21 UTC, merged